[package]
name = "gameoflife"
version = "0.1.0"
authors = ["Do Duy <doduycm@gmail.com>"]

[dependencies]
relm = "0.9.6"
relm-derive = "0.9.2"
tokio-core = "0.1.8"
cairo-rs = "0.1.3"
gdk = "0.5.3"
serde = "1.0.8"
serde_json = "1.0.2"
serde_derive = "1.0.8"
chrono = "*"

[dependencies.gtk]
version = "0.1.3"
features = ["v3_16"]
